import { Toaster } from "@/components/ui/toaster";
import "../app/style/global.css";
import type { Metadata } from "next";
import { Arvo } from "next/font/google";
import ThemeProvider from "@/context/ThemeProvider";

export const metadata: Metadata = {
  title: "Gen_A",
  description: "Generated by create next app",
};

const arvo = Arvo({
  weight: ["400", "700"],
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" style={{colorScheme: "light"}}>
      <body className={arvo.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
